# ----------------------- DATABASE CONFIGURATION
DB_USERNAME: "root"
DB_PASSWORD: ""
DB_HOST: "mysql://bf06dfa1a8a1d7:9375f104@us-cdbr-east-02.cleardb.com/heroku_cd0435688c2b32d?reconnect=true"
DB_NAME: "time-off-dev"
DB_MAX_CONNECTION: "32"
DB_MIN_CONNECTION: "4"

# ----------------------- ECHO CONFIGURATION
PORT: "3022"